### ISSUE TITLE
Problem: rate-limiting is not supported

### ISSUE THREAD

**Issue by jorikvankemenade** [artefactual-labs/enduro#12]
In [this issue](https://github.com/archivematica/Issues/issues/1010) I started a discussion on how package queueing and rate-limiting are handled for packages submitted to Archivematica. I think it is important to have this discussion, but I also think that it is important to realize that we should always keep reasonable usage in mind. 

One thing I consider a valid use case, but not a reasonable usage of the API, is if you have a large back-log of transfers. Let's say I have an enduro instance running with a watched directory, and I have a backlog of 200 files, I will copy all 200 files to the watched directory. When I do this the polling mechanism will detect 200 new transfers, and start them immediately. I think it is not hard to imagine in how many ways this will break any reasonable Archivematica instance.

To cover this case I would think that it makes sense to have some sort of rate-limiting mechanism in Enduro. I haven't given this a lot of thought as of yet, but I wanted to gather opinions and see if there is any interest or even plans for this feature. 

In the past, I have used two ways to limit the number of transfers I send to Archivematica. By using a fixed time delay, and by having a number of processing slots available. I think the latter option is better, but more complex and requires more work. Please let me know what you guys think. what is already in the planning, and if you want me to come up with a more concrete proposal.

**Comment by sevein** [comment]
Thanks for writing this up. Your description in https://github.com/archivematica/Issues/issues/1010 is spot on and something that we should consider in further releases of Archivematica.

When it comes to Enduro, I looked briefly at ways of doing resource usage control but didn't get too far. Similar to the idea of processing slots that you mention, I thought that we could have a Cadence workflow execution per resource (pipeline) implementing a lock that can be operated from processing workflows via signals (similar to [the mutex example](https://github.com/uber-common/cadence-samples/tree/master/cmd/samples/recipes/mutex)). The problem with that approach is that the cardinality of pipeline to executions trying to use the lock could be very high and Cadence may not handle that very well if you suddenly submit say 50k transfers.

An alternative could be to implement a weighted semaphore somewhere else, e.g. Redis? Processing workflows would have activities that acquire and release. Since the acquire operation could potential take a long time, the activity would be implemented with heartbeats so it does not time out.

This is something that I'd love to see implemented but that we don't have time to tackle so if you're interested please go ahead!

**Comment by sevein** [comment]
To be clear, I think that a fix in Archivematica would be ideal. I see the alternatives I suggested as quick workarounds that we can implement in Enduro for the time being.

**Comment by jorikvankemenade** [comment]
@sevein thanks for having a look and giving some possible solutions. I [posted](https://github.com/archivematica/Issues/issues/1010#issuecomment-559603761) a possible approach in the discussion thread. Maybe you can see what you think of that approach. Do you see any obvious downsides or problems?

**Comment by jorikvankemenade** [comment]
Nice start to resolving this in #18. 
Will do some additional testing and possible work on this later this month,

**Comment by sevein** [comment]
Cool, thanks @jorikvankemenade. FYI I'm planning to add the queued status sometime this week. Possibly also adding a new timestamp field to persist the startup timestamp.

**Comment by sevein** [comment]
Fixed in v0.19.1.
