### ISSUE TITLE
Discussion: change file permissions  in bundle_activity

### ISSUE THREAD

**Issue by jorikvankemenade** [artefactual-labs/enduro#13]
In 416f3fe the `bundle_activity` is configured to change the file permissions to `775`. In my current setup, this is impossible - Enduro is not allowed to `chmod` a file. In parallel to this question, I am trying to fix that. 

But I was wondering, what is the rationale behind both changing the file permissions and why this specific one? The distributed filesystem that we use for hosting al Archivematica related material has a default `644` permission. I would think should be sufficient?

**Comment by jorikvankemenade** [comment]
With some debugging, I found that the main problem was with my deployment. However, if you don't mind I would still like to know what the rationale is behind the permissions change.

**Comment by sevein** [comment]
I figured that in most environments the user creating the transfer (enduro) wouldn't be the same user that reads it (archivematica). If I gave it a 644, it wouldn't be possible to traverse at all. The default is also inconvenient because it leaves "others" out. If you had concerns about sharing too much, you could still remove the execution bit from any of the parents.

**Comment by jorikvankemenade** [comment]
Thanks for the clarification, it makes sense to me and is indeed a very flexible solution. Like I said, in my case, the problem was caused by mixing up credentials between nodes that are connected to the same distributed file system. So for me the "defaults" work!
