### ISSUE TITLE
Problem: mandatory activities can't prompt users

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/enduro#38]
We need certain activities to prompt the user after errors occur. In Cadence, that's possible via [activity asynchronous completion](https://cadenceworkflow.io/docs/07_goclient/12_activity_async_completion). The goal is to give users different choices, e.g. retry, give up...

E.g. NHA-specific activities `hari` and `prod` are essential for them to run properly. If they don't, logging the error isn't enough. We need to give users the ability to identify collections in these state and have the ability to choose how to proceed.

**Comment by joel-simpson** [comment]
When some activities fail, we don't know the exact state of what happened (e.g. if Archivematica can't provide a clear success or failed result from any given transfer). In these cases, the 'retry' function needs to start from the beginning of the workflow (or potentially from the last clean known state). 

In other cases, if an Activity fails, it should be possible to retry just that activity (or 'retry the workflow from that activity onward). The examples @sevein provides are those -- updating HARI and production system could be retried later; ideally that would be the case because the current behaviour is to retry from the start, which creates another AIP (which isn't needed because the previous activities completed successfully and an AIP is already stored). The current behaviour effectively creates duplicate AIPS. 

I hadn't considered the need to prompt users for a choice, but that does make sense. Ideally users can choose to retry, or choose to abandon the workflow. Showing a status of 'abandoned' would be useful because the Enduro dashboard is like a queue for users to manage errors; they want to work through every collection that is in an error or failed state until they show completed successfully, or have chosen to abandon them.

**Comment by sevein** [comment]
I'm closing this since we have async completion in v0.22.0. We may want to use the same solution in other activities but we can do that as a separate issue.
